// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snlynntywqodggviethp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNubHlubnR5d3FvZGdndmlldGhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NzI4MDUsImV4cCI6MjA2NzU0ODgwNX0.8fHRAgtClyQ58QhsIhaqti9LTfjXqWrxqKbbo67L9lg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});